/**
 * pdfExporter — generate a print-friendly HTML document and trigger window.print()
 *
 * Strategy (ADR-18): instead of bundling jsPDF + html2canvas, we render a print-
 * targeted HTML document, open it in a new window, and call `window.print()`.
 * The browser's built-in PDF engine handles vector text, Korean fonts, and page
 * breaks natively. Resulting PDF has selectable text and zero font glyph issues.
 *
 * Layout:
 *   - Cover page: project name, generated date, file/domain counts
 *   - Table of contents: list of domains with page hint
 *   - Per-domain section (one per domain) with description, key symbols, file list
 *   - Root-level overview SVG on page 2
 *   - Each cached drilldown level appears after its parent domain
 *   - @media print rules force page breaks between sections
 */
import type { SemanticLevel } from '$lib/types/semantic';
import { renderSemanticLevelSvg } from './semanticSvgRenderer';

export interface PdfExportInput {
	projectName: string;
	rootLevel: SemanticLevel;
	cache?: Map<string, SemanticLevel>;
	generatedAt?: Date;
}

function escapeHtml(s: string): string {
	return s
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#39;');
}

function uniqueFileCount(level: SemanticLevel): number {
	const seen = new Set<string>();
	for (const n of level.nodes) for (const fp of n.filePaths) seen.add(fp);
	return seen.size;
}

export function buildPrintDocument(input: PdfExportInput): string {
	const projectName = escapeHtml(input.projectName || 'project');
	const date = (input.generatedAt ?? new Date()).toISOString().slice(0, 10);
	const root = input.rootLevel;
	const cache = input.cache;
	const totalFiles = uniqueFileCount(root);
	const domainCount = root.nodes.length;

	const rootSvg = renderSemanticLevelSvg(root, { theme: 'light', cache });

	const sections: string[] = [];

	// Cover
	sections.push(`
<section class="page cover">
	<div class="cover-inner">
		<div class="cover-eyebrow">Architecture Document</div>
		<h1 class="cover-title">${projectName}</h1>
		<div class="cover-meta">
			<div><strong>Generated</strong> ${escapeHtml(date)}</div>
			<div><strong>Domains</strong> ${domainCount}</div>
			<div><strong>Files</strong> ${totalFiles}</div>
		</div>
		<div class="cover-footer">Generated by ropeman</div>
	</div>
</section>`);

	// Table of contents
	sections.push(`
<section class="page toc">
	<h2>Table of Contents</h2>
	<ol class="toc-list">
		<li><span class="toc-label">Overview</span></li>
		${root.nodes
			.map(
				(n) =>
					`<li><span class="toc-label">${escapeHtml(n.label)}</span>${
						cache?.get(n.id) ? ' <span class="toc-tag">+ sub-domains</span>' : ''
					}</li>`
			)
			.join('\n\t\t')}
	</ol>
</section>`);

	// Overview page
	sections.push(`
<section class="page overview">
	<h2>Overview</h2>
	<div class="diagram">${rootSvg.svg}</div>
	<p class="caption">High-level domains and their relationships.</p>
</section>`);

	// Per-domain sections
	for (const node of root.nodes) {
		const sub = cache?.get(node.id);
		const subSvg = sub ? renderSemanticLevelSvg(sub, { theme: 'light', cache }) : null;

		sections.push(`
<section class="page domain">
	<header class="domain-header">
		<div class="domain-color" style="background:${escapeHtml(node.color || '#475569')}"></div>
		<h2>${escapeHtml(node.label)}</h2>
	</header>
	${node.description ? `<p class="domain-desc">${escapeHtml(node.description)}</p>` : ''}
	<dl class="domain-facts">
		<dt>Files</dt><dd>${node.fileCount}</dd>
		${node.keySymbols.length > 0 ? `<dt>Key symbols</dt><dd>${node.keySymbols.map((s) => `<code>${escapeHtml(s)}</code>`).join(' ')}</dd>` : ''}
	</dl>
	${
		node.filePaths.length > 0
			? `<details open><summary>File list</summary><ul class="file-list">${node.filePaths
					.map((fp) => `<li><code>${escapeHtml(fp)}</code></li>`)
					.join('')}</ul></details>`
			: ''
	}
	${
		subSvg
			? `<div class="sub-section">
		<h3>Sub-domains</h3>
		<div class="diagram">${subSvg.svg}</div>
	</div>`
			: ''
	}
</section>`);
	}

	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${projectName} — Architecture</title>
<style>
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; background: #f8fafc; color: #0f172a; font-family: ui-sans-serif, system-ui, -apple-system, "Helvetica Neue", "Apple SD Gothic Neo", "Noto Sans KR", sans-serif; }
.page { padding: 48px; min-height: 100vh; max-width: 800px; margin: 0 auto 24px auto; background: #ffffff; box-shadow: 0 1px 4px rgba(15, 23, 42, 0.08); }
h2 { font-size: 22px; margin: 0 0 16px 0; color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
h3 { font-size: 16px; margin: 24px 0 12px 0; color: #334155; }
.cover { display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 64px; background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%); }
.cover-inner { text-align: center; max-width: 600px; }
.cover-eyebrow { text-transform: uppercase; letter-spacing: 0.15em; font-size: 12px; color: #64748b; margin-bottom: 24px; }
.cover-title { font-size: 42px; font-weight: 700; margin: 0 0 48px 0; color: #0f172a; word-break: break-word; }
.cover-meta { display: flex; flex-direction: column; gap: 12px; font-size: 14px; color: #334155; }
.cover-meta strong { color: #64748b; font-weight: 500; margin-right: 8px; }
.cover-footer { margin-top: 64px; font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.1em; }
.toc-list { font-size: 14px; line-height: 2; padding-left: 20px; }
.toc-label { color: #0f172a; }
.toc-tag { color: #64748b; font-size: 11px; margin-left: 8px; }
.diagram { margin: 16px 0; text-align: center; }
.diagram svg { max-width: 100%; height: auto; }
.caption { font-size: 12px; color: #64748b; text-align: center; margin-top: 4px; }
.domain-header { display: flex; align-items: center; gap: 12px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-bottom: 16px; }
.domain-header h2 { border: none; padding: 0; margin: 0; }
.domain-color { width: 12px; height: 24px; border-radius: 3px; flex-shrink: 0; }
.domain-desc { font-size: 14px; line-height: 1.6; color: #334155; }
.domain-facts { display: grid; grid-template-columns: 120px 1fr; gap: 8px 16px; font-size: 13px; margin: 16px 0; }
.domain-facts dt { color: #64748b; font-weight: 500; }
.domain-facts dd { margin: 0; color: #0f172a; }
.domain-facts code { background: #f1f5f9; padding: 2px 6px; border-radius: 3px; font-size: 12px; font-family: ui-monospace, "SF Mono", Menlo, monospace; margin-right: 4px; }
details { margin-top: 16px; }
summary { font-size: 13px; font-weight: 500; cursor: pointer; color: #475569; padding: 4px 0; }
.file-list { font-size: 12px; line-height: 1.7; padding-left: 20px; column-count: 2; column-gap: 24px; }
.file-list code { background: #f1f5f9; padding: 1px 5px; border-radius: 3px; font-family: ui-monospace, monospace; font-size: 11px; word-break: break-all; }
.sub-section { margin-top: 32px; padding-top: 24px; border-top: 1px dashed #cbd5e1; }
@media print {
	html, body { background: #ffffff; }
	.page { box-shadow: none; margin: 0; max-width: none; padding: 24mm 18mm; min-height: auto; page-break-after: always; }
	.page:last-child { page-break-after: auto; }
	.cover { padding: 48mm 24mm; }
	@page { margin: 0; size: A4; }
}
.print-controls { position: fixed; top: 16px; right: 16px; background: #0f172a; color: #f1f5f9; padding: 12px 16px; border-radius: 6px; box-shadow: 0 4px 12px rgba(0,0,0,0.2); display: flex; gap: 8px; align-items: center; font-size: 13px; z-index: 9999; }
.print-controls button { background: #38bdf8; color: #0f172a; border: none; padding: 6px 14px; border-radius: 4px; cursor: pointer; font-weight: 600; font-size: 13px; }
.print-controls button:hover { background: #7dd3fc; }
@media print { .print-controls { display: none; } }
</style>
</head>
<body>
<div class="print-controls">
	<span>Press Ctrl/Cmd+P, then "Save as PDF"</span>
	<button onclick="window.print()">Print</button>
</div>
${sections.join('\n')}
</body>
</html>
`;
}

export async function exportAsPdf(input: PdfExportInput): Promise<void> {
	const html = buildPrintDocument(input);
	// Open in a new tab via blob URL — avoids document.write deprecation
	// and lets the user keep the source app intact.
	const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
	const url = URL.createObjectURL(blob);
	const win = window.open(url, '_blank');
	if (!win) {
		// Pop-up blocked: fall back to download
		const a = document.createElement('a');
		a.href = url;
		a.download = `${sanitizeFilename(input.projectName) || 'project'}-architecture-print.html`;
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		setTimeout(() => URL.revokeObjectURL(url), 60_000);
		return;
	}
	// Auto-trigger print after the new window's document is ready.
	const tryPrint = () => {
		try {
			win.focus();
			win.print();
		} catch {
			// User can use the in-page Print button instead
		}
	};
	win.addEventListener('load', tryPrint);
	// Fallback: some browsers fire load before listener attaches
	setTimeout(() => {
		if (!win.closed && win.document.readyState === 'complete') tryPrint();
	}, 500);
	setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function sanitizeFilename(name: string): string {
	return name.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '');
}
